"""ESPHome YAML fragments, composed rather than templated.

A flat substitution template cannot express this configuration: LED type
varies per display, several displays may share one addressable strip, and
buttons are optional. So each piece is built independently and the pieces are
merged under their top-level keys.

Output is assembled as text rather than dumped from a YAML library because
ESPHome YAML carries `!lambda` and `!secret` tags and reads much better with
comments — both of which a round-tripping dumper would mangle or drop.
"""

from __future__ import annotations

import re
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from collections.abc import Iterable, Sequence

    from ..boards.profile import BoardProfile
    from ..spec import ButtonSpec, DisplaySpec, YamlRequest

__all__ = [
    "addressable_light_blocks",
    "base_block",
    "button_blocks",
    "display_blocks",
    "raw_rgb_blocks",
    "slug",
]

#: Frequency for the meter PWM. The movement's own mechanical inertia damps
#: the ripple at this rate, so no RC filter is needed.
LEDC_FREQUENCY = "1000Hz"


def slug(value: str) -> str:
    """Turn a display or button name into a valid ESPHome id."""
    cleaned = re.sub(r"[^a-z0-9]+", "_", value.strip().lower()).strip("_")
    if not cleaned:
        return "unnamed"
    if cleaned[0].isdigit():
        cleaned = f"n{cleaned}"
    return cleaned


def _pin(number: int) -> str:
    """Render a GPIO number the way ESPHome expects it."""
    return f"GPIO{number}"


def base_block(request: YamlRequest, board: BoardProfile) -> str:
    """Build the device, platform, logger, API, OTA and Wi-Fi preamble."""
    node = slug(request.device_name).replace("_", "-")
    return f"""\
# Generated by the Analog Displays integration for Home Assistant.
#
# This firmware exposes generic entities only. Which sensor feeds which meter,
# how it is calibrated, and what the buttons do all live in Home Assistant and
# can be changed there without reflashing.

esphome:
  name: {node}
  friendly_name: {request.device_name}

{board.platform}:
  board: {board.board}
  framework:
    type: {board.framework}

logger:

api:
  encryption:
    key: !secret analog_displays_api_key

ota:
  - platform: esphome
    password: !secret analog_displays_ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:
    ssid: "{request.device_name} Fallback"

captive_portal:
"""


def display_blocks(displays: Sequence[DisplaySpec]) -> tuple[list[str], list[str]]:
    """Build the ``output`` and ``number`` entries that move the meters.

    The template number must never call ``number.set`` on itself inside its own
    ``set_action``: that recurses until the ESP32 crashes. With
    ``optimistic: true`` ESPHome publishes the state itself, so the action only
    has to drive the output.
    """
    outputs: list[str] = []
    numbers: list[str] = []

    for display in displays:
        name = slug(display.name)
        outputs.append(
            f"""\
  - platform: ledc
    id: out_{name}
    pin: {_pin(display.pin)}
    frequency: {LEDC_FREQUENCY}"""
        )
        numbers.append(
            f"""\
  - platform: template
    name: "{display.name}"
    id: {name}
    min_value: 0
    max_value: 1
    step: 0.001
    optimistic: true
    set_action:
      - output.set_level:
          id: out_{name}
          level: !lambda return x;"""
        )

    return outputs, numbers


def addressable_light_blocks(displays: Sequence[DisplaySpec]) -> list[str]:
    """Build one strip per shared data pin, plus a partition per display.

    Several displays sharing one strip is the normal case — one data line, one
    LED per meter — and ``partition`` is ESPHome's way to carve that strip into
    independently controllable segments.
    """
    by_pin: dict[int, list[DisplaySpec]] = {}
    for display in displays:
        led = display.led
        if led is not None and led.kind == "addressable":
            by_pin.setdefault(led.data_pin, []).append(display)

    blocks: list[str] = []
    for data_pin in sorted(by_pin):
        on_pin = by_pin[data_pin]
        num_leds = max(display.led.index for display in on_pin) + 1  # type: ignore[union-attr]
        blocks.append(
            f"""\
  - platform: esp32_rmt_led_strip
    id: strip_gpio{data_pin}
    pin: {_pin(data_pin)}
    num_leds: {num_leds}
    chipset: ws2812
    rgb_order: GRB
    internal: true"""
        )

    for display in displays:
        led = display.led
        if led is None or led.kind != "addressable":
            continue
        name = slug(display.name)
        blocks.append(
            f"""\
  - platform: partition
    name: "{display.name} LED"
    id: led_{name}
    segments:
      - id: strip_gpio{led.data_pin}
        from: {led.index}
        to: {led.index}"""
        )

    return blocks


def raw_rgb_blocks(
    displays: Sequence[DisplaySpec],
) -> tuple[list[str], list[str]]:
    """Build three PWM outputs and an ``rgb`` light for each raw-RGB display."""
    outputs: list[str] = []
    lights: list[str] = []

    for display in displays:
        led = display.led
        if led is None or led.kind != "raw_rgb":
            continue

        name = slug(display.name)
        channels = (
            ("red", led.red_pin),
            ("green", led.green_pin),
            ("blue", led.blue_pin),
        )
        for channel, pin in channels:
            outputs.append(
                f"""\
  - platform: ledc
    id: out_{name}_{channel}
    pin: {_pin(pin)}"""
            )
        lights.append(
            f"""\
  - platform: rgb
    name: "{display.name} LED"
    id: led_{name}
    red: out_{name}_red
    green: out_{name}_green
    blue: out_{name}_blue"""
        )

    return outputs, lights


def button_blocks(buttons: Sequence[ButtonSpec]) -> tuple[list[str], list[str]]:
    """Build the ``binary_sensor`` and ``event`` entries for the buttons.

    A plain button gives Home Assistant a ``binary_sensor``. A multi-click
    button also gets an ``event`` entity, so a preset binding can distinguish
    a single press from a double or a long one without the user inventing
    event names.
    """
    sensors: list[str] = []
    events: list[str] = []

    for button in buttons:
        name = slug(button.name)
        block = f"""\
  - platform: gpio
    name: "{button.name}"
    id: {name}
    pin:
      number: {_pin(button.pin)}
      mode:
        input: true
        pullup: true
      inverted: true"""

        if button.multi_click:
            block += f"""
    on_multi_click:
      - timing:
          - ON for at most 0.4s
          - OFF for at least 0.35s
        then:
          - event.trigger:
              id: {name}_event
              event_type: single
      - timing:
          - ON for at most 0.4s
          - OFF for at most 0.3s
          - ON for at most 0.4s
          - OFF for at least 0.35s
        then:
          - event.trigger:
              id: {name}_event
              event_type: double
      - timing:
          - ON for at least 0.8s
        then:
          - event.trigger:
              id: {name}_event
              event_type: long"""
            events.append(
                f"""\
  - platform: template
    name: "{button.name} clicks"
    id: {name}_event
    event_types:
      - single
      - double
      - long"""
            )

        sensors.append(block)

    return sensors, events


def section(key: str, entries: Iterable[str]) -> str:
    """Render one top-level YAML key, or nothing if it has no entries."""
    items = list(entries)
    if not items:
        return ""
    body = "\n".join(items)
    return f"{key}:\n{body}\n"
